/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 130
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SPACE = 1,
  aux_sym_root_token1 = 2,
  anon_sym_PIPE = 3,
  sym_format_space = 4,
  sym_depth_mark = 5,
  anon_sym_PIPE_EQ_DASH = 6,
  anon_sym_PIPE_EQ_EQ = 7,
  aux_sym_directory_name_token1 = 8,
  aux_sym_file_name_token1 = 9,
  aux_sym_file_name_token2 = 10,
  aux_sym_file_name_token3 = 11,
  sym_comment_open = 12,
  sym_comment_closed = 13,
  sym_comment_text = 14,
  aux_sym_comment_newline_token1 = 15,
  aux_sym_comment_newline_token2 = 16,
  sym_source_file = 17,
  sym__item = 18,
  sym_root = 19,
  sym_root_bar = 20,
  sym_entry_bar = 21,
  sym_scope_delimiter_open = 22,
  sym_scope_delimiter_closed = 23,
  sym_file_entry = 24,
  sym_directory_entry = 25,
  sym_directory_name = 26,
  sym_file_name = 27,
  sym_content_block = 28,
  sym_comment = 29,
  sym_comment_newline = 30,
  sym_comment_bar = 31,
  sym_comment_content = 32,
  aux_sym_file_entry_repeat1 = 33,
  aux_sym_directory_name_repeat1 = 34,
  aux_sym_content_block_repeat1 = 35,
  aux_sym_comment_newline_repeat1 = 36,
  aux_sym_comment_newline_repeat2 = 37,
  aux_sym_comment_content_repeat1 = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SPACE] = " ",
  [aux_sym_root_token1] = "root_token1",
  [anon_sym_PIPE] = "|",
  [sym_format_space] = "format_space",
  [sym_depth_mark] = "depth_mark",
  [anon_sym_PIPE_EQ_DASH] = "|=-",
  [anon_sym_PIPE_EQ_EQ] = "|==",
  [aux_sym_directory_name_token1] = "directory_name_token1",
  [aux_sym_file_name_token1] = "file_name_token1",
  [aux_sym_file_name_token2] = "file_name_token2",
  [aux_sym_file_name_token3] = "file_name_token3",
  [sym_comment_open] = "comment_open",
  [sym_comment_closed] = "comment_closed",
  [sym_comment_text] = "comment_text",
  [aux_sym_comment_newline_token1] = "comment_newline_token1",
  [aux_sym_comment_newline_token2] = "comment_newline_token2",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [sym_root] = "root",
  [sym_root_bar] = "root_bar",
  [sym_entry_bar] = "entry_bar",
  [sym_scope_delimiter_open] = "scope_delimiter_open",
  [sym_scope_delimiter_closed] = "scope_delimiter_closed",
  [sym_file_entry] = "file_entry",
  [sym_directory_entry] = "directory_entry",
  [sym_directory_name] = "directory_name",
  [sym_file_name] = "file_name",
  [sym_content_block] = "content_block",
  [sym_comment] = "comment",
  [sym_comment_newline] = "comment_newline",
  [sym_comment_bar] = "comment_bar",
  [sym_comment_content] = "comment_content",
  [aux_sym_file_entry_repeat1] = "file_entry_repeat1",
  [aux_sym_directory_name_repeat1] = "directory_name_repeat1",
  [aux_sym_content_block_repeat1] = "content_block_repeat1",
  [aux_sym_comment_newline_repeat1] = "comment_newline_repeat1",
  [aux_sym_comment_newline_repeat2] = "comment_newline_repeat2",
  [aux_sym_comment_content_repeat1] = "comment_content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [aux_sym_root_token1] = aux_sym_root_token1,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_format_space] = sym_format_space,
  [sym_depth_mark] = sym_depth_mark,
  [anon_sym_PIPE_EQ_DASH] = anon_sym_PIPE_EQ_DASH,
  [anon_sym_PIPE_EQ_EQ] = anon_sym_PIPE_EQ_EQ,
  [aux_sym_directory_name_token1] = aux_sym_directory_name_token1,
  [aux_sym_file_name_token1] = aux_sym_file_name_token1,
  [aux_sym_file_name_token2] = aux_sym_file_name_token2,
  [aux_sym_file_name_token3] = aux_sym_file_name_token3,
  [sym_comment_open] = sym_comment_open,
  [sym_comment_closed] = sym_comment_closed,
  [sym_comment_text] = sym_comment_text,
  [aux_sym_comment_newline_token1] = aux_sym_comment_newline_token1,
  [aux_sym_comment_newline_token2] = aux_sym_comment_newline_token2,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [sym_root] = sym_root,
  [sym_root_bar] = sym_root_bar,
  [sym_entry_bar] = sym_entry_bar,
  [sym_scope_delimiter_open] = sym_scope_delimiter_open,
  [sym_scope_delimiter_closed] = sym_scope_delimiter_closed,
  [sym_file_entry] = sym_file_entry,
  [sym_directory_entry] = sym_directory_entry,
  [sym_directory_name] = sym_directory_name,
  [sym_file_name] = sym_file_name,
  [sym_content_block] = sym_content_block,
  [sym_comment] = sym_comment,
  [sym_comment_newline] = sym_comment_newline,
  [sym_comment_bar] = sym_comment_bar,
  [sym_comment_content] = sym_comment_content,
  [aux_sym_file_entry_repeat1] = aux_sym_file_entry_repeat1,
  [aux_sym_directory_name_repeat1] = aux_sym_directory_name_repeat1,
  [aux_sym_content_block_repeat1] = aux_sym_content_block_repeat1,
  [aux_sym_comment_newline_repeat1] = aux_sym_comment_newline_repeat1,
  [aux_sym_comment_newline_repeat2] = aux_sym_comment_newline_repeat2,
  [aux_sym_comment_content_repeat1] = aux_sym_comment_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_root_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_format_space] = {
    .visible = true,
    .named = true,
  },
  [sym_depth_mark] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE_EQ_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_directory_name_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_file_name_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_file_name_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_file_name_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_comment_open] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_closed] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_newline_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_newline_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_root] = {
    .visible = true,
    .named = true,
  },
  [sym_root_bar] = {
    .visible = true,
    .named = true,
  },
  [sym_entry_bar] = {
    .visible = true,
    .named = true,
  },
  [sym_scope_delimiter_open] = {
    .visible = true,
    .named = true,
  },
  [sym_scope_delimiter_closed] = {
    .visible = true,
    .named = true,
  },
  [sym_file_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_directory_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_directory_name] = {
    .visible = true,
    .named = true,
  },
  [sym_file_name] = {
    .visible = true,
    .named = true,
  },
  [sym_content_block] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_bar] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_file_entry_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_directory_name_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_newline_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_newline_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_bridge = 1,
  field_contents = 2,
  field_formatspace = 3,
  field_leaf = 4,
  field_name = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_bridge] = "bridge",
  [field_contents] = "contents",
  [field_formatspace] = "formatspace",
  [field_leaf] = "leaf",
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 3},
  [6] = {.index = 10, .length = 3},
  [7] = {.index = 13, .length = 3},
  [8] = {.index = 16, .length = 4},
  [9] = {.index = 20, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_formatspace, 1},
  [1] =
    {field_contents, 4},
    {field_name, 2},
  [3] =
    {field_contents, 5},
    {field_name, 2},
  [5] =
    {field_leaf, 1},
    {field_name, 3},
  [7] =
    {field_bridge, 1},
    {field_leaf, 2},
    {field_name, 4},
  [10] =
    {field_contents, 6},
    {field_leaf, 1},
    {field_name, 3},
  [13] =
    {field_contents, 7},
    {field_leaf, 1},
    {field_name, 3},
  [16] =
    {field_bridge, 1},
    {field_contents, 7},
    {field_leaf, 2},
    {field_name, 4},
  [20] =
    {field_bridge, 1},
    {field_contents, 8},
    {field_leaf, 2},
    {field_name, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 3,
  [11] = 6,
  [12] = 5,
  [13] = 7,
  [14] = 8,
  [15] = 9,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 19,
  [21] = 19,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 26,
  [28] = 24,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 33,
  [37] = 35,
  [38] = 32,
  [39] = 34,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 50,
  [64] = 62,
  [65] = 51,
  [66] = 52,
  [67] = 54,
  [68] = 55,
  [69] = 56,
  [70] = 57,
  [71] = 58,
  [72] = 59,
  [73] = 60,
  [74] = 61,
  [75] = 75,
  [76] = 75,
  [77] = 77,
  [78] = 47,
  [79] = 48,
  [80] = 53,
  [81] = 77,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 91,
  [93] = 93,
  [94] = 83,
  [95] = 88,
  [96] = 93,
  [97] = 97,
  [98] = 98,
  [99] = 97,
  [100] = 86,
  [101] = 85,
  [102] = 98,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 108,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 109,
  [116] = 61,
  [117] = 113,
  [118] = 118,
  [119] = 114,
  [120] = 120,
  [121] = 104,
  [122] = 118,
  [123] = 60,
  [124] = 124,
  [125] = 118,
  [126] = 105,
  [127] = 113,
  [128] = 128,
  [129] = 129,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(18);
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '\'') ADVANCE(35);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '|') ADVANCE(24);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(46);
      if (lookahead == '|') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0) ADVANCE(45);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead == '|') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead == '|') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == ' ') ADVANCE(28);
      if (lookahead == '>') ADVANCE(39);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(21);
      if (lookahead == '>') ADVANCE(39);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '|') ADVANCE(45);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(19);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(7);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(37);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '\'') ADVANCE(38);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '-') ADVANCE(30);
      END_STATE();
    case 11:
      if (lookahead == '-') ADVANCE(30);
      if (lookahead == '=') ADVANCE(31);
      END_STATE();
    case 12:
      if (lookahead == '/') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == '=') ADVANCE(31);
      END_STATE();
    case 14:
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '|') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      END_STATE();
    case 15:
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '|') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(15);
      END_STATE();
    case 16:
      if (eof) ADVANCE(18);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '|') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(16);
      END_STATE();
    case 17:
      if (eof) ADVANCE(18);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '|') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_root_token1);
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == ' ') ADVANCE(28);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_root_token1);
      if (lookahead == '\n') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '=') ADVANCE(11);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '=') ADVANCE(11);
      if (lookahead == '|') ADVANCE(40);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '=') ADVANCE(13);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '=') ADVANCE(10);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '|') ADVANCE(40);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_format_space);
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == ' ') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_depth_mark);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_PIPE_EQ_DASH);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_PIPE_EQ_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_directory_name_token1);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == '"' ||
          lookahead == '\'') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(12);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_directory_name_token1);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(12);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_file_name_token1);
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_file_name_token1);
      if (lookahead == '\'') ADVANCE(35);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_file_name_token1);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_file_name_token2);
      if (lookahead == '"') ADVANCE(37);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(8);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_file_name_token3);
      if (lookahead == '\'') ADVANCE(38);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(9);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_comment_open);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_comment_closed);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_comment_text);
      if (lookahead == '\n') ADVANCE(46);
      if (lookahead == ' ') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '|') ADVANCE(45);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_comment_text);
      if (lookahead == '\n') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '|') ADVANCE(45);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_comment_text);
      if (lookahead == '\n') ADVANCE(48);
      if (lookahead == ' ') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '|') ADVANCE(45);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_comment_text);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '|') ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_comment_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_comment_newline_token1);
      if (lookahead == '\n') ADVANCE(46);
      if (lookahead == ' ') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(42);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_comment_newline_token1);
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead == ' ') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_comment_newline_token1);
      if (lookahead == '\n') ADVANCE(48);
      if (lookahead == ' ') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(43);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_comment_newline_token2);
      if (lookahead == '\n') ADVANCE(48);
      if (lookahead == ' ') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(43);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 16},
  [2] = {.lex_state = 16},
  [3] = {.lex_state = 16},
  [4] = {.lex_state = 16},
  [5] = {.lex_state = 16},
  [6] = {.lex_state = 16},
  [7] = {.lex_state = 16},
  [8] = {.lex_state = 16},
  [9] = {.lex_state = 16},
  [10] = {.lex_state = 16},
  [11] = {.lex_state = 14},
  [12] = {.lex_state = 14},
  [13] = {.lex_state = 16},
  [14] = {.lex_state = 16},
  [15] = {.lex_state = 16},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 49},
  [23] = {.lex_state = 49},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 49},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 49},
  [30] = {.lex_state = 49},
  [31] = {.lex_state = 49},
  [32] = {.lex_state = 17},
  [33] = {.lex_state = 17},
  [34] = {.lex_state = 17},
  [35] = {.lex_state = 17},
  [36] = {.lex_state = 15},
  [37] = {.lex_state = 15},
  [38] = {.lex_state = 15},
  [39] = {.lex_state = 15},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 4},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 5},
  [48] = {.lex_state = 5},
  [49] = {.lex_state = 5},
  [50] = {.lex_state = 16},
  [51] = {.lex_state = 16},
  [52] = {.lex_state = 16},
  [53] = {.lex_state = 5},
  [54] = {.lex_state = 16},
  [55] = {.lex_state = 16},
  [56] = {.lex_state = 16},
  [57] = {.lex_state = 16},
  [58] = {.lex_state = 16},
  [59] = {.lex_state = 16},
  [60] = {.lex_state = 16},
  [61] = {.lex_state = 16},
  [62] = {.lex_state = 14},
  [63] = {.lex_state = 14},
  [64] = {.lex_state = 16},
  [65] = {.lex_state = 14},
  [66] = {.lex_state = 14},
  [67] = {.lex_state = 14},
  [68] = {.lex_state = 14},
  [69] = {.lex_state = 14},
  [70] = {.lex_state = 14},
  [71] = {.lex_state = 14},
  [72] = {.lex_state = 14},
  [73] = {.lex_state = 14},
  [74] = {.lex_state = 14},
  [75] = {.lex_state = 5},
  [76] = {.lex_state = 5},
  [77] = {.lex_state = 5},
  [78] = {.lex_state = 5},
  [79] = {.lex_state = 5},
  [80] = {.lex_state = 5},
  [81] = {.lex_state = 5},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 7},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 16},
  [90] = {.lex_state = 16},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 7},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 7},
  [100] = {.lex_state = 7},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 7},
  [104] = {.lex_state = 5},
  [105] = {.lex_state = 5},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 5},
  [109] = {.lex_state = 5},
  [110] = {.lex_state = 5},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 7},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 5},
  [115] = {.lex_state = 5},
  [116] = {.lex_state = 5},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 6},
  [119] = {.lex_state = 5},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 5},
  [122] = {.lex_state = 6},
  [123] = {.lex_state = 5},
  [124] = {.lex_state = 5},
  [125] = {.lex_state = 6},
  [126] = {.lex_state = 5},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 5},
  [129] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_depth_mark] = ACTIONS(1),
    [anon_sym_PIPE_EQ_DASH] = ACTIONS(1),
    [anon_sym_PIPE_EQ_EQ] = ACTIONS(1),
    [aux_sym_directory_name_token1] = ACTIONS(1),
    [aux_sym_file_name_token1] = ACTIONS(1),
    [aux_sym_file_name_token2] = ACTIONS(1),
    [aux_sym_file_name_token3] = ACTIONS(1),
    [sym_comment_open] = ACTIONS(1),
    [sym_comment_closed] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(120),
    [sym_root] = STATE(106),
    [sym_root_bar] = STATE(103),
    [anon_sym_PIPE] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(5), 1,
      anon_sym_PIPE,
    ACTIONS(7), 1,
      sym_comment_open,
    STATE(85), 1,
      sym_entry_bar,
    STATE(111), 1,
      sym_content_block,
    STATE(6), 5,
      sym__item,
      sym_file_entry,
      sym_directory_entry,
      sym_comment,
      aux_sym_content_block_repeat1,
  [20] = 5,
    ACTIONS(5), 1,
      anon_sym_PIPE,
    ACTIONS(9), 1,
      sym_comment_open,
    STATE(95), 1,
      sym_content_block,
    STATE(101), 1,
      sym_entry_bar,
    STATE(11), 5,
      sym__item,
      sym_file_entry,
      sym_directory_entry,
      sym_comment,
      aux_sym_content_block_repeat1,
  [40] = 5,
    ACTIONS(5), 1,
      anon_sym_PIPE,
    ACTIONS(7), 1,
      sym_comment_open,
    STATE(85), 1,
      sym_entry_bar,
    STATE(107), 1,
      sym_content_block,
    STATE(6), 5,
      sym__item,
      sym_file_entry,
      sym_directory_entry,
      sym_comment,
      aux_sym_content_block_repeat1,
  [60] = 5,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      anon_sym_PIPE,
    ACTIONS(16), 1,
      sym_comment_open,
    STATE(85), 1,
      sym_entry_bar,
    STATE(5), 5,
      sym__item,
      sym_file_entry,
      sym_directory_entry,
      sym_comment,
      aux_sym_content_block_repeat1,
  [80] = 5,
    ACTIONS(5), 1,
      anon_sym_PIPE,
    ACTIONS(7), 1,
      sym_comment_open,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(85), 1,
      sym_entry_bar,
    STATE(5), 5,
      sym__item,
      sym_file_entry,
      sym_directory_entry,
      sym_comment,
      aux_sym_content_block_repeat1,
  [100] = 5,
    ACTIONS(5), 1,
      anon_sym_PIPE,
    ACTIONS(9), 1,
      sym_comment_open,
    STATE(92), 1,
      sym_content_block,
    STATE(101), 1,
      sym_entry_bar,
    STATE(11), 5,
      sym__item,
      sym_file_entry,
      sym_directory_entry,
      sym_comment,
      aux_sym_content_block_repeat1,
  [120] = 5,
    ACTIONS(5), 1,
      anon_sym_PIPE,
    ACTIONS(9), 1,
      sym_comment_open,
    STATE(96), 1,
      sym_content_block,
    STATE(101), 1,
      sym_entry_bar,
    STATE(11), 5,
      sym__item,
      sym_file_entry,
      sym_directory_entry,
      sym_comment,
      aux_sym_content_block_repeat1,
  [140] = 5,
    ACTIONS(5), 1,
      anon_sym_PIPE,
    ACTIONS(9), 1,
      sym_comment_open,
    STATE(83), 1,
      sym_content_block,
    STATE(101), 1,
      sym_entry_bar,
    STATE(11), 5,
      sym__item,
      sym_file_entry,
      sym_directory_entry,
      sym_comment,
      aux_sym_content_block_repeat1,
  [160] = 5,
    ACTIONS(5), 1,
      anon_sym_PIPE,
    ACTIONS(9), 1,
      sym_comment_open,
    STATE(88), 1,
      sym_content_block,
    STATE(101), 1,
      sym_entry_bar,
    STATE(11), 5,
      sym__item,
      sym_file_entry,
      sym_directory_entry,
      sym_comment,
      aux_sym_content_block_repeat1,
  [180] = 5,
    ACTIONS(9), 1,
      sym_comment_open,
    ACTIONS(19), 1,
      anon_sym_PIPE_EQ_EQ,
    ACTIONS(21), 1,
      anon_sym_PIPE,
    STATE(101), 1,
      sym_entry_bar,
    STATE(12), 5,
      sym__item,
      sym_file_entry,
      sym_directory_entry,
      sym_comment,
      aux_sym_content_block_repeat1,
  [200] = 5,
    ACTIONS(11), 1,
      anon_sym_PIPE_EQ_EQ,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    ACTIONS(26), 1,
      sym_comment_open,
    STATE(101), 1,
      sym_entry_bar,
    STATE(12), 5,
      sym__item,
      sym_file_entry,
      sym_directory_entry,
      sym_comment,
      aux_sym_content_block_repeat1,
  [220] = 5,
    ACTIONS(5), 1,
      anon_sym_PIPE,
    ACTIONS(9), 1,
      sym_comment_open,
    STATE(91), 1,
      sym_content_block,
    STATE(101), 1,
      sym_entry_bar,
    STATE(11), 5,
      sym__item,
      sym_file_entry,
      sym_directory_entry,
      sym_comment,
      aux_sym_content_block_repeat1,
  [240] = 5,
    ACTIONS(5), 1,
      anon_sym_PIPE,
    ACTIONS(9), 1,
      sym_comment_open,
    STATE(93), 1,
      sym_content_block,
    STATE(101), 1,
      sym_entry_bar,
    STATE(11), 5,
      sym__item,
      sym_file_entry,
      sym_directory_entry,
      sym_comment,
      aux_sym_content_block_repeat1,
  [260] = 5,
    ACTIONS(5), 1,
      anon_sym_PIPE,
    ACTIONS(9), 1,
      sym_comment_open,
    STATE(94), 1,
      sym_content_block,
    STATE(101), 1,
      sym_entry_bar,
    STATE(11), 5,
      sym__item,
      sym_file_entry,
      sym_directory_entry,
      sym_comment,
      aux_sym_content_block_repeat1,
  [280] = 7,
    ACTIONS(29), 1,
      anon_sym_PIPE,
    ACTIONS(32), 1,
      sym_comment_closed,
    ACTIONS(34), 1,
      sym_comment_text,
    ACTIONS(37), 1,
      aux_sym_comment_newline_token1,
    STATE(25), 1,
      sym_comment_bar,
    STATE(45), 1,
      aux_sym_comment_newline_repeat1,
    STATE(16), 2,
      sym_comment_newline,
      aux_sym_comment_content_repeat1,
  [303] = 7,
    ACTIONS(40), 1,
      anon_sym_PIPE,
    ACTIONS(42), 1,
      sym_comment_closed,
    ACTIONS(44), 1,
      sym_comment_text,
    ACTIONS(46), 1,
      aux_sym_comment_newline_token1,
    STATE(25), 1,
      sym_comment_bar,
    STATE(45), 1,
      aux_sym_comment_newline_repeat1,
    STATE(18), 2,
      sym_comment_newline,
      aux_sym_comment_content_repeat1,
  [326] = 7,
    ACTIONS(40), 1,
      anon_sym_PIPE,
    ACTIONS(46), 1,
      aux_sym_comment_newline_token1,
    ACTIONS(48), 1,
      sym_comment_closed,
    ACTIONS(50), 1,
      sym_comment_text,
    STATE(25), 1,
      sym_comment_bar,
    STATE(45), 1,
      aux_sym_comment_newline_repeat1,
    STATE(16), 2,
      sym_comment_newline,
      aux_sym_comment_content_repeat1,
  [349] = 7,
    ACTIONS(40), 1,
      anon_sym_PIPE,
    ACTIONS(52), 1,
      sym_comment_closed,
    ACTIONS(54), 1,
      aux_sym_comment_newline_token1,
    STATE(17), 1,
      sym_comment_newline,
    STATE(25), 1,
      sym_comment_bar,
    STATE(45), 1,
      aux_sym_comment_newline_repeat1,
    STATE(113), 1,
      sym_comment_content,
  [371] = 7,
    ACTIONS(40), 1,
      anon_sym_PIPE,
    ACTIONS(54), 1,
      aux_sym_comment_newline_token1,
    ACTIONS(56), 1,
      sym_comment_closed,
    STATE(17), 1,
      sym_comment_newline,
    STATE(25), 1,
      sym_comment_bar,
    STATE(45), 1,
      aux_sym_comment_newline_repeat1,
    STATE(127), 1,
      sym_comment_content,
  [393] = 7,
    ACTIONS(40), 1,
      anon_sym_PIPE,
    ACTIONS(54), 1,
      aux_sym_comment_newline_token1,
    ACTIONS(58), 1,
      sym_comment_closed,
    STATE(17), 1,
      sym_comment_newline,
    STATE(25), 1,
      sym_comment_bar,
    STATE(45), 1,
      aux_sym_comment_newline_repeat1,
    STATE(117), 1,
      sym_comment_content,
  [415] = 3,
    ACTIONS(62), 1,
      aux_sym_comment_newline_token2,
    STATE(22), 1,
      aux_sym_comment_newline_repeat2,
    ACTIONS(60), 4,
      anon_sym_PIPE,
      sym_comment_closed,
      sym_comment_text,
      aux_sym_comment_newline_token1,
  [428] = 3,
    ACTIONS(67), 1,
      aux_sym_comment_newline_token2,
    STATE(22), 1,
      aux_sym_comment_newline_repeat2,
    ACTIONS(65), 4,
      anon_sym_PIPE,
      sym_comment_closed,
      sym_comment_text,
      aux_sym_comment_newline_token1,
  [441] = 4,
    ACTIONS(69), 1,
      aux_sym_directory_name_token1,
    STATE(47), 1,
      sym_directory_name,
    STATE(48), 1,
      sym_file_name,
    ACTIONS(71), 3,
      aux_sym_file_name_token1,
      aux_sym_file_name_token2,
      aux_sym_file_name_token3,
  [456] = 3,
    ACTIONS(75), 1,
      aux_sym_comment_newline_token2,
    STATE(29), 1,
      aux_sym_comment_newline_repeat2,
    ACTIONS(73), 4,
      anon_sym_PIPE,
      sym_comment_closed,
      sym_comment_text,
      aux_sym_comment_newline_token1,
  [469] = 4,
    ACTIONS(69), 1,
      aux_sym_directory_name_token1,
    STATE(75), 1,
      sym_directory_name,
    STATE(81), 1,
      sym_file_name,
    ACTIONS(71), 3,
      aux_sym_file_name_token1,
      aux_sym_file_name_token2,
      aux_sym_file_name_token3,
  [484] = 4,
    ACTIONS(69), 1,
      aux_sym_directory_name_token1,
    STATE(76), 1,
      sym_directory_name,
    STATE(77), 1,
      sym_file_name,
    ACTIONS(71), 3,
      aux_sym_file_name_token1,
      aux_sym_file_name_token2,
      aux_sym_file_name_token3,
  [499] = 4,
    ACTIONS(69), 1,
      aux_sym_directory_name_token1,
    STATE(78), 1,
      sym_directory_name,
    STATE(79), 1,
      sym_file_name,
    ACTIONS(71), 3,
      aux_sym_file_name_token1,
      aux_sym_file_name_token2,
      aux_sym_file_name_token3,
  [514] = 3,
    ACTIONS(67), 1,
      aux_sym_comment_newline_token2,
    STATE(22), 1,
      aux_sym_comment_newline_repeat2,
    ACTIONS(77), 4,
      anon_sym_PIPE,
      sym_comment_closed,
      sym_comment_text,
      aux_sym_comment_newline_token1,
  [527] = 3,
    ACTIONS(79), 1,
      aux_sym_comment_newline_token2,
    STATE(23), 1,
      aux_sym_comment_newline_repeat2,
    ACTIONS(77), 4,
      anon_sym_PIPE,
      sym_comment_closed,
      sym_comment_text,
      aux_sym_comment_newline_token1,
  [540] = 1,
    ACTIONS(81), 5,
      anon_sym_PIPE,
      sym_comment_closed,
      sym_comment_text,
      aux_sym_comment_newline_token1,
      aux_sym_comment_newline_token2,
  [548] = 4,
    ACTIONS(85), 1,
      anon_sym_PIPE,
    ACTIONS(87), 1,
      anon_sym_PIPE_EQ_DASH,
    STATE(9), 1,
      sym_scope_delimiter_open,
    ACTIONS(83), 2,
      ts_builtin_sym_end,
      sym_comment_open,
  [562] = 4,
    ACTIONS(87), 1,
      anon_sym_PIPE_EQ_DASH,
    ACTIONS(91), 1,
      anon_sym_PIPE,
    STATE(8), 1,
      sym_scope_delimiter_open,
    ACTIONS(89), 2,
      ts_builtin_sym_end,
      sym_comment_open,
  [576] = 4,
    ACTIONS(87), 1,
      anon_sym_PIPE_EQ_DASH,
    ACTIONS(95), 1,
      anon_sym_PIPE,
    STATE(7), 1,
      sym_scope_delimiter_open,
    ACTIONS(93), 2,
      ts_builtin_sym_end,
      sym_comment_open,
  [590] = 4,
    ACTIONS(87), 1,
      anon_sym_PIPE_EQ_DASH,
    ACTIONS(99), 1,
      anon_sym_PIPE,
    STATE(10), 1,
      sym_scope_delimiter_open,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      sym_comment_open,
  [604] = 4,
    ACTIONS(87), 1,
      anon_sym_PIPE_EQ_DASH,
    ACTIONS(91), 1,
      anon_sym_PIPE,
    STATE(14), 1,
      sym_scope_delimiter_open,
    ACTIONS(89), 2,
      anon_sym_PIPE_EQ_EQ,
      sym_comment_open,
  [618] = 4,
    ACTIONS(87), 1,
      anon_sym_PIPE_EQ_DASH,
    ACTIONS(99), 1,
      anon_sym_PIPE,
    STATE(3), 1,
      sym_scope_delimiter_open,
    ACTIONS(97), 2,
      anon_sym_PIPE_EQ_EQ,
      sym_comment_open,
  [632] = 4,
    ACTIONS(85), 1,
      anon_sym_PIPE,
    ACTIONS(87), 1,
      anon_sym_PIPE_EQ_DASH,
    STATE(15), 1,
      sym_scope_delimiter_open,
    ACTIONS(83), 2,
      anon_sym_PIPE_EQ_EQ,
      sym_comment_open,
  [646] = 4,
    ACTIONS(87), 1,
      anon_sym_PIPE_EQ_DASH,
    ACTIONS(95), 1,
      anon_sym_PIPE,
    STATE(13), 1,
      sym_scope_delimiter_open,
    ACTIONS(93), 2,
      anon_sym_PIPE_EQ_EQ,
      sym_comment_open,
  [660] = 3,
    ACTIONS(103), 1,
      sym_format_space,
    STATE(40), 1,
      aux_sym_directory_name_repeat1,
    ACTIONS(101), 2,
      aux_sym_root_token1,
      sym_comment_open,
  [671] = 3,
    ACTIONS(108), 1,
      sym_format_space,
    STATE(40), 1,
      aux_sym_directory_name_repeat1,
    ACTIONS(106), 2,
      aux_sym_root_token1,
      sym_comment_open,
  [682] = 3,
    ACTIONS(112), 1,
      sym_format_space,
    STATE(41), 1,
      aux_sym_directory_name_repeat1,
    ACTIONS(110), 2,
      aux_sym_root_token1,
      sym_comment_open,
  [693] = 3,
    ACTIONS(108), 1,
      sym_format_space,
    STATE(40), 1,
      aux_sym_directory_name_repeat1,
    ACTIONS(114), 2,
      aux_sym_root_token1,
      sym_comment_open,
  [704] = 3,
    ACTIONS(118), 1,
      sym_format_space,
    STATE(43), 1,
      aux_sym_directory_name_repeat1,
    ACTIONS(116), 2,
      aux_sym_root_token1,
      sym_comment_open,
  [715] = 4,
    ACTIONS(40), 1,
      anon_sym_PIPE,
    ACTIONS(120), 1,
      aux_sym_comment_newline_token1,
    STATE(30), 1,
      sym_comment_bar,
    STATE(82), 1,
      aux_sym_comment_newline_repeat1,
  [728] = 3,
    ACTIONS(122), 1,
      aux_sym_root_token1,
    ACTIONS(124), 1,
      sym_comment_open,
    STATE(124), 1,
      sym_comment,
  [738] = 3,
    ACTIONS(124), 1,
      sym_comment_open,
    ACTIONS(126), 1,
      aux_sym_root_token1,
    STATE(110), 1,
      sym_comment,
  [748] = 3,
    ACTIONS(124), 1,
      sym_comment_open,
    ACTIONS(128), 1,
      aux_sym_root_token1,
    STATE(115), 1,
      sym_comment,
  [758] = 3,
    ACTIONS(124), 1,
      sym_comment_open,
    ACTIONS(130), 1,
      aux_sym_root_token1,
    STATE(128), 1,
      sym_comment,
  [768] = 1,
    ACTIONS(132), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_comment_open,
  [774] = 1,
    ACTIONS(134), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_comment_open,
  [780] = 1,
    ACTIONS(136), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_comment_open,
  [786] = 3,
    ACTIONS(124), 1,
      sym_comment_open,
    ACTIONS(138), 1,
      aux_sym_root_token1,
    STATE(119), 1,
      sym_comment,
  [796] = 1,
    ACTIONS(140), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_comment_open,
  [802] = 1,
    ACTIONS(142), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_comment_open,
  [808] = 1,
    ACTIONS(144), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_comment_open,
  [814] = 1,
    ACTIONS(146), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_comment_open,
  [820] = 1,
    ACTIONS(148), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_comment_open,
  [826] = 1,
    ACTIONS(150), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_comment_open,
  [832] = 1,
    ACTIONS(152), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_comment_open,
  [838] = 1,
    ACTIONS(154), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_comment_open,
  [844] = 2,
    ACTIONS(156), 1,
      anon_sym_PIPE,
    ACTIONS(158), 2,
      anon_sym_PIPE_EQ_EQ,
      sym_comment_open,
  [852] = 2,
    ACTIONS(160), 1,
      anon_sym_PIPE,
    ACTIONS(132), 2,
      anon_sym_PIPE_EQ_EQ,
      sym_comment_open,
  [860] = 1,
    ACTIONS(158), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_comment_open,
  [866] = 2,
    ACTIONS(162), 1,
      anon_sym_PIPE,
    ACTIONS(134), 2,
      anon_sym_PIPE_EQ_EQ,
      sym_comment_open,
  [874] = 2,
    ACTIONS(164), 1,
      anon_sym_PIPE,
    ACTIONS(136), 2,
      anon_sym_PIPE_EQ_EQ,
      sym_comment_open,
  [882] = 2,
    ACTIONS(166), 1,
      anon_sym_PIPE,
    ACTIONS(140), 2,
      anon_sym_PIPE_EQ_EQ,
      sym_comment_open,
  [890] = 2,
    ACTIONS(168), 1,
      anon_sym_PIPE,
    ACTIONS(142), 2,
      anon_sym_PIPE_EQ_EQ,
      sym_comment_open,
  [898] = 2,
    ACTIONS(170), 1,
      anon_sym_PIPE,
    ACTIONS(144), 2,
      anon_sym_PIPE_EQ_EQ,
      sym_comment_open,
  [906] = 2,
    ACTIONS(172), 1,
      anon_sym_PIPE,
    ACTIONS(146), 2,
      anon_sym_PIPE_EQ_EQ,
      sym_comment_open,
  [914] = 2,
    ACTIONS(174), 1,
      anon_sym_PIPE,
    ACTIONS(148), 2,
      anon_sym_PIPE_EQ_EQ,
      sym_comment_open,
  [922] = 2,
    ACTIONS(176), 1,
      anon_sym_PIPE,
    ACTIONS(150), 2,
      anon_sym_PIPE_EQ_EQ,
      sym_comment_open,
  [930] = 2,
    ACTIONS(178), 1,
      anon_sym_PIPE,
    ACTIONS(152), 2,
      anon_sym_PIPE_EQ_EQ,
      sym_comment_open,
  [938] = 2,
    ACTIONS(180), 1,
      anon_sym_PIPE,
    ACTIONS(154), 2,
      anon_sym_PIPE_EQ_EQ,
      sym_comment_open,
  [946] = 3,
    ACTIONS(124), 1,
      sym_comment_open,
    ACTIONS(182), 1,
      aux_sym_root_token1,
    STATE(121), 1,
      sym_comment,
  [956] = 3,
    ACTIONS(124), 1,
      sym_comment_open,
    ACTIONS(184), 1,
      aux_sym_root_token1,
    STATE(104), 1,
      sym_comment,
  [966] = 3,
    ACTIONS(124), 1,
      sym_comment_open,
    ACTIONS(186), 1,
      aux_sym_root_token1,
    STATE(105), 1,
      sym_comment,
  [976] = 3,
    ACTIONS(124), 1,
      sym_comment_open,
    ACTIONS(188), 1,
      aux_sym_root_token1,
    STATE(108), 1,
      sym_comment,
  [986] = 3,
    ACTIONS(124), 1,
      sym_comment_open,
    ACTIONS(190), 1,
      aux_sym_root_token1,
    STATE(109), 1,
      sym_comment,
  [996] = 3,
    ACTIONS(124), 1,
      sym_comment_open,
    ACTIONS(192), 1,
      aux_sym_root_token1,
    STATE(114), 1,
      sym_comment,
  [1006] = 3,
    ACTIONS(124), 1,
      sym_comment_open,
    ACTIONS(194), 1,
      aux_sym_root_token1,
    STATE(126), 1,
      sym_comment,
  [1016] = 3,
    ACTIONS(196), 1,
      anon_sym_PIPE,
    ACTIONS(198), 1,
      aux_sym_comment_newline_token1,
    STATE(82), 1,
      aux_sym_comment_newline_repeat1,
  [1026] = 2,
    ACTIONS(201), 1,
      anon_sym_PIPE_EQ_EQ,
    STATE(57), 1,
      sym_scope_delimiter_closed,
  [1033] = 2,
    ACTIONS(203), 1,
      sym_depth_mark,
    STATE(84), 1,
      aux_sym_file_entry_repeat1,
  [1040] = 2,
    ACTIONS(206), 1,
      sym_depth_mark,
    STATE(98), 1,
      aux_sym_file_entry_repeat1,
  [1047] = 2,
    ACTIONS(208), 1,
      anon_sym_SPACE,
    ACTIONS(210), 1,
      sym_depth_mark,
  [1054] = 2,
    ACTIONS(69), 1,
      aux_sym_directory_name_token1,
    STATE(46), 1,
      sym_directory_name,
  [1061] = 2,
    ACTIONS(201), 1,
      anon_sym_PIPE_EQ_EQ,
    STATE(59), 1,
      sym_scope_delimiter_closed,
  [1068] = 1,
    ACTIONS(212), 2,
      anon_sym_PIPE,
      sym_comment_open,
  [1073] = 1,
    ACTIONS(214), 2,
      anon_sym_PIPE,
      sym_comment_open,
  [1078] = 2,
    ACTIONS(216), 1,
      anon_sym_PIPE_EQ_EQ,
    STATE(67), 1,
      sym_scope_delimiter_closed,
  [1085] = 2,
    ACTIONS(201), 1,
      anon_sym_PIPE_EQ_EQ,
    STATE(54), 1,
      sym_scope_delimiter_closed,
  [1092] = 2,
    ACTIONS(216), 1,
      anon_sym_PIPE_EQ_EQ,
    STATE(69), 1,
      sym_scope_delimiter_closed,
  [1099] = 2,
    ACTIONS(216), 1,
      anon_sym_PIPE_EQ_EQ,
    STATE(70), 1,
      sym_scope_delimiter_closed,
  [1106] = 2,
    ACTIONS(216), 1,
      anon_sym_PIPE_EQ_EQ,
    STATE(72), 1,
      sym_scope_delimiter_closed,
  [1113] = 2,
    ACTIONS(201), 1,
      anon_sym_PIPE_EQ_EQ,
    STATE(56), 1,
      sym_scope_delimiter_closed,
  [1120] = 2,
    ACTIONS(210), 1,
      sym_depth_mark,
    ACTIONS(218), 1,
      anon_sym_SPACE,
  [1127] = 2,
    ACTIONS(220), 1,
      sym_depth_mark,
    STATE(84), 1,
      aux_sym_file_entry_repeat1,
  [1134] = 2,
    ACTIONS(210), 1,
      sym_depth_mark,
    ACTIONS(222), 1,
      anon_sym_SPACE,
  [1141] = 2,
    ACTIONS(210), 1,
      sym_depth_mark,
    ACTIONS(224), 1,
      anon_sym_SPACE,
  [1148] = 2,
    ACTIONS(226), 1,
      sym_depth_mark,
    STATE(102), 1,
      aux_sym_file_entry_repeat1,
  [1155] = 2,
    ACTIONS(228), 1,
      sym_depth_mark,
    STATE(84), 1,
      aux_sym_file_entry_repeat1,
  [1162] = 1,
    ACTIONS(230), 1,
      anon_sym_SPACE,
  [1166] = 1,
    ACTIONS(232), 1,
      aux_sym_root_token1,
  [1170] = 1,
    ACTIONS(234), 1,
      aux_sym_root_token1,
  [1174] = 1,
    ACTIONS(236), 1,
      ts_builtin_sym_end,
  [1178] = 1,
    ACTIONS(238), 1,
      ts_builtin_sym_end,
  [1182] = 1,
    ACTIONS(240), 1,
      aux_sym_root_token1,
  [1186] = 1,
    ACTIONS(242), 1,
      aux_sym_root_token1,
  [1190] = 1,
    ACTIONS(244), 1,
      aux_sym_root_token1,
  [1194] = 1,
    ACTIONS(246), 1,
      ts_builtin_sym_end,
  [1198] = 1,
    ACTIONS(248), 1,
      anon_sym_SPACE,
  [1202] = 1,
    ACTIONS(250), 1,
      sym_comment_closed,
  [1206] = 1,
    ACTIONS(252), 1,
      aux_sym_root_token1,
  [1210] = 1,
    ACTIONS(254), 1,
      aux_sym_root_token1,
  [1214] = 1,
    ACTIONS(154), 1,
      aux_sym_root_token1,
  [1218] = 1,
    ACTIONS(256), 1,
      sym_comment_closed,
  [1222] = 1,
    ACTIONS(258), 1,
      sym_comment_text,
  [1226] = 1,
    ACTIONS(260), 1,
      aux_sym_root_token1,
  [1230] = 1,
    ACTIONS(262), 1,
      ts_builtin_sym_end,
  [1234] = 1,
    ACTIONS(264), 1,
      aux_sym_root_token1,
  [1238] = 1,
    ACTIONS(266), 1,
      sym_comment_text,
  [1242] = 1,
    ACTIONS(152), 1,
      aux_sym_root_token1,
  [1246] = 1,
    ACTIONS(268), 1,
      aux_sym_root_token1,
  [1250] = 1,
    ACTIONS(270), 1,
      sym_comment_text,
  [1254] = 1,
    ACTIONS(272), 1,
      aux_sym_root_token1,
  [1258] = 1,
    ACTIONS(274), 1,
      sym_comment_closed,
  [1262] = 1,
    ACTIONS(276), 1,
      aux_sym_root_token1,
  [1266] = 1,
    ACTIONS(278), 1,
      sym_depth_mark,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 20,
  [SMALL_STATE(4)] = 40,
  [SMALL_STATE(5)] = 60,
  [SMALL_STATE(6)] = 80,
  [SMALL_STATE(7)] = 100,
  [SMALL_STATE(8)] = 120,
  [SMALL_STATE(9)] = 140,
  [SMALL_STATE(10)] = 160,
  [SMALL_STATE(11)] = 180,
  [SMALL_STATE(12)] = 200,
  [SMALL_STATE(13)] = 220,
  [SMALL_STATE(14)] = 240,
  [SMALL_STATE(15)] = 260,
  [SMALL_STATE(16)] = 280,
  [SMALL_STATE(17)] = 303,
  [SMALL_STATE(18)] = 326,
  [SMALL_STATE(19)] = 349,
  [SMALL_STATE(20)] = 371,
  [SMALL_STATE(21)] = 393,
  [SMALL_STATE(22)] = 415,
  [SMALL_STATE(23)] = 428,
  [SMALL_STATE(24)] = 441,
  [SMALL_STATE(25)] = 456,
  [SMALL_STATE(26)] = 469,
  [SMALL_STATE(27)] = 484,
  [SMALL_STATE(28)] = 499,
  [SMALL_STATE(29)] = 514,
  [SMALL_STATE(30)] = 527,
  [SMALL_STATE(31)] = 540,
  [SMALL_STATE(32)] = 548,
  [SMALL_STATE(33)] = 562,
  [SMALL_STATE(34)] = 576,
  [SMALL_STATE(35)] = 590,
  [SMALL_STATE(36)] = 604,
  [SMALL_STATE(37)] = 618,
  [SMALL_STATE(38)] = 632,
  [SMALL_STATE(39)] = 646,
  [SMALL_STATE(40)] = 660,
  [SMALL_STATE(41)] = 671,
  [SMALL_STATE(42)] = 682,
  [SMALL_STATE(43)] = 693,
  [SMALL_STATE(44)] = 704,
  [SMALL_STATE(45)] = 715,
  [SMALL_STATE(46)] = 728,
  [SMALL_STATE(47)] = 738,
  [SMALL_STATE(48)] = 748,
  [SMALL_STATE(49)] = 758,
  [SMALL_STATE(50)] = 768,
  [SMALL_STATE(51)] = 774,
  [SMALL_STATE(52)] = 780,
  [SMALL_STATE(53)] = 786,
  [SMALL_STATE(54)] = 796,
  [SMALL_STATE(55)] = 802,
  [SMALL_STATE(56)] = 808,
  [SMALL_STATE(57)] = 814,
  [SMALL_STATE(58)] = 820,
  [SMALL_STATE(59)] = 826,
  [SMALL_STATE(60)] = 832,
  [SMALL_STATE(61)] = 838,
  [SMALL_STATE(62)] = 844,
  [SMALL_STATE(63)] = 852,
  [SMALL_STATE(64)] = 860,
  [SMALL_STATE(65)] = 866,
  [SMALL_STATE(66)] = 874,
  [SMALL_STATE(67)] = 882,
  [SMALL_STATE(68)] = 890,
  [SMALL_STATE(69)] = 898,
  [SMALL_STATE(70)] = 906,
  [SMALL_STATE(71)] = 914,
  [SMALL_STATE(72)] = 922,
  [SMALL_STATE(73)] = 930,
  [SMALL_STATE(74)] = 938,
  [SMALL_STATE(75)] = 946,
  [SMALL_STATE(76)] = 956,
  [SMALL_STATE(77)] = 966,
  [SMALL_STATE(78)] = 976,
  [SMALL_STATE(79)] = 986,
  [SMALL_STATE(80)] = 996,
  [SMALL_STATE(81)] = 1006,
  [SMALL_STATE(82)] = 1016,
  [SMALL_STATE(83)] = 1026,
  [SMALL_STATE(84)] = 1033,
  [SMALL_STATE(85)] = 1040,
  [SMALL_STATE(86)] = 1047,
  [SMALL_STATE(87)] = 1054,
  [SMALL_STATE(88)] = 1061,
  [SMALL_STATE(89)] = 1068,
  [SMALL_STATE(90)] = 1073,
  [SMALL_STATE(91)] = 1078,
  [SMALL_STATE(92)] = 1085,
  [SMALL_STATE(93)] = 1092,
  [SMALL_STATE(94)] = 1099,
  [SMALL_STATE(95)] = 1106,
  [SMALL_STATE(96)] = 1113,
  [SMALL_STATE(97)] = 1120,
  [SMALL_STATE(98)] = 1127,
  [SMALL_STATE(99)] = 1134,
  [SMALL_STATE(100)] = 1141,
  [SMALL_STATE(101)] = 1148,
  [SMALL_STATE(102)] = 1155,
  [SMALL_STATE(103)] = 1162,
  [SMALL_STATE(104)] = 1166,
  [SMALL_STATE(105)] = 1170,
  [SMALL_STATE(106)] = 1174,
  [SMALL_STATE(107)] = 1178,
  [SMALL_STATE(108)] = 1182,
  [SMALL_STATE(109)] = 1186,
  [SMALL_STATE(110)] = 1190,
  [SMALL_STATE(111)] = 1194,
  [SMALL_STATE(112)] = 1198,
  [SMALL_STATE(113)] = 1202,
  [SMALL_STATE(114)] = 1206,
  [SMALL_STATE(115)] = 1210,
  [SMALL_STATE(116)] = 1214,
  [SMALL_STATE(117)] = 1218,
  [SMALL_STATE(118)] = 1222,
  [SMALL_STATE(119)] = 1226,
  [SMALL_STATE(120)] = 1230,
  [SMALL_STATE(121)] = 1234,
  [SMALL_STATE(122)] = 1238,
  [SMALL_STATE(123)] = 1242,
  [SMALL_STATE(124)] = 1246,
  [SMALL_STATE(125)] = 1250,
  [SMALL_STATE(126)] = 1254,
  [SMALL_STATE(127)] = 1258,
  [SMALL_STATE(128)] = 1262,
  [SMALL_STATE(129)] = 1266,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_block_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_block_repeat1, 2, 0, 0), SHIFT_REPEAT(129),
  [16] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_block_repeat1, 2, 0, 0), SHIFT_REPEAT(118),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content_block, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(129),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_block_repeat1, 2, 0, 0), SHIFT_REPEAT(129),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_block_repeat1, 2, 0, 0), SHIFT_REPEAT(125),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_content_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [32] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_content_repeat1, 2, 0, 0),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_content_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_content_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_content, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_content, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(123),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_newline_repeat2, 2, 0, 0),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_newline_repeat2, 2, 0, 0), SHIFT_REPEAT(22),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_newline, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_newline, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_newline, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_bar, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directory_entry, 6, 0, 5),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directory_entry, 6, 0, 5),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directory_entry, 6, 0, 4),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directory_entry, 6, 0, 4),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directory_entry, 5, 0, 4),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directory_entry, 5, 0, 4),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directory_entry, 7, 0, 5),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directory_entry, 7, 0, 5),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_directory_name_repeat1, 2, 0, 0),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_directory_name_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_file_name, 2, 0, 1),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_file_name, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directory_name, 2, 0, 1),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directory_name, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(122),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_entry, 6, 0, 4),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_entry, 6, 0, 5),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_entry, 7, 0, 5),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directory_entry, 8, 0, 6),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope_delimiter_closed, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directory_entry, 9, 0, 7),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directory_entry, 9, 0, 8),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope_delimiter_closed, 3, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directory_entry, 10, 0, 9),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 4, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_file_entry, 5, 0, 4),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_entry, 5, 0, 4),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_file_entry, 6, 0, 4),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_file_entry, 6, 0, 5),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_file_entry, 7, 0, 5),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directory_entry, 8, 0, 6),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scope_delimiter_closed, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directory_entry, 9, 0, 7),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directory_entry, 9, 0, 8),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scope_delimiter_closed, 3, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directory_entry, 10, 0, 9),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 4, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_newline_repeat1, 2, 0, 0),
  [198] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comment_newline_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_entry_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_file_entry_repeat1, 1, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope_delimiter_open, 3, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope_delimiter_open, 2, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root, 6, 0, 3),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root, 5, 0, 2),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_bar, 1, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [262] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry_bar, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_liotree(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "liotree",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
